Chapter8
parkchu/study-computing-systems pull request #2
Opened 2021-05-16 23:17 UTC by parkchu

ㅎㅅㅎ

2021-05-17 07:22 UTC, javajigi requested changes
구현 잘 했네요. 💯 💯
진심 칭찬하고 싶네..

인터페이스 활용 관련해 피드백 하나 남겼다.
여기서 한 단계 더 도전해 보면 좋겠다.

2021-05-17 07:22 UTC, javajigi commented on projects/07/VMTranslator/src/main/kotlin/vmTranslator/VMTranslator.kt
> +        }
```
interface Command { 
    fun isSupports(command: String): Boolean

    fun write(args: String?): String
 }
 ```

 위와 같이 구현한 후 goto 문을 구현해야 하는 클래스라면..

 ```
 class GotoCommand: Command {
    fun isSupports(command: String): Boolean {
        return // command가 CommandType.C_GOTO 이라면 true
    }

    fun write(args: String?): String {
        // CodeWriter의 writeGoto를 이곳에 구현
    }
 }
 ```

위와 같이 각 command별 구현 클래스를 구현하고...

listOf(LabelCommand(), GotoCommand(), InitCommand().....)
와 같이 list로 관리한다면 이곳의 if문과 CodeWriter의 각 command별 메소드를 모두 제거할 수 있지 않을까?

한번 도전해 보면 좋겠다.

2021-05-17 23:56 UTC, parkchu commented on projects/07/VMTranslator/src/main/kotlin/vmTranslator/VMTranslator.kt
> +        }
오 오 오 오 오 오!!!!
신기하구만 그랴😄
빨리 해보고 싶다ㅏㅏㅏㅏ

2021-05-18 15:05 UTC, parkchu commented
@javajigi 
CodeWrite 와 Command 들의 관계가 너무 끈끈하구만...

2021-05-19 07:47 UTC, javajigi approved these changes
오호.
예상보다 리팩토링한 코드가 아주 좋소 💯 
각 command별로 테스트 코드까지 있었다면 더 좋았겠지만 이 정도에서 merge하겠소

2021-05-19 07:47 UTC, merged