Chapter10
parkchu/study-computing-systems pull request #4
Opened 2021-06-10 06:39 UTC by parkchu

최대한 리펙토링 해 보았습니다.
TokensTool 의 filterComment  부분은 리펙토링 하지 못했습니다 ㅠ

2021-06-10 07:52 UTC, javajigi requested changes
이 정도 수준이면 깔끔하게 구현 잘 했네. 💯 
소소한 피드백 몇 개 남겨봤다.

2021-06-10 07:52 UTC, javajigi commented on projects/10/Complier/src/main/kotlin/jackTokenizer/JackTokenizer.kt
> +
`fun next(): Token`을 반환하고, 
Token 객체가 isIdentifier), isSymbol(), isKeyworkd와 같은 메서드를 가지면 어떨까?

2021-06-10 07:52 UTC, javajigi commented on projects/10/Complier/src/main/kotlin/compilationEngine/CompilationEngine.kt
> +    private val strings = mutableListOf<String>()
strings보다 더 의미있는 이름으로 작성하면 어떨까?

2021-06-10 07:52 UTC, javajigi commented on projects/10/Complier/src/test/kotlin/compilationEngine/CompilationEngineTest.kt
> +    fun compileSubroutine() {
테스트 코드 구현 👍

2021-06-15 07:33 UTC, parkchu commented on projects/10/Complier/src/main/kotlin/jackTokenizer/JackTokenizer.kt
> +
token 을 반환하게 구현하면 Compilers, CompilationEngine 에서 구현하기 힘들것 같아서 JackTokenizer 가 가지고  있는 currentToken 을 사용하도록 구현했습니다. 그 후 isXxx 메서드 들은 Token 이 가지도록 리펙토링 했습니다!

2021-06-15 08:43 UTC, javajigi approved these changes
피드백 반영하느라 수고했다. 💯 
다음 미션도 화이팅
포기하지 말고 끝까지 도전해 성공하기를...

2021-06-15 08:43 UTC, merged